# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Dugonzal <dugonzal@student.42urduliz.com>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/21 23:39:30 by Dugonzal          #+#    #+#              #
#    Updated: 2024/01/22 17:57:10 by Dugonzal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


version: '3.8'

services:
    proxy:
      container_name:  nginx
      build: .
      ports:
      - 443:443 
      networks:
      - nginx 

networks:
  nginx:
      name: nginx 
      driver: bridge
