print("<form action=\"/cgi/geeks.py\" method=\"post\">")
print("\r\r\r<input type=\"text\" name=\"your_name\" placeholder=\"Your Name\" /><br>")
print("\r\r\r<input type=\"text\" name=\"company_name\" placeholder=\"Company Name\" /><br>")
print("\r\r\r<input type=\"submit\" value=\"Submit\" />")
print("</form>")