name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: webserver
      run: ./webserv

    - name: Install dependencies
      run: make

    - name: Run check
      run: make re

    - name: Run distcheck
      run: make distcheck
