
name: Hello World

on:
  push:
    branches:
      - D-0 

jobs:
  build:
    runs-on: archlinux/base 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: make an test 
      run: sudo pacman -Syu cppunit zsh  &&  make re
